# Copyright (C) 2012 Mattias Ugelvik
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# Colors are specified in RGB, in a list. If there are 4 elements, then the
# 4th is the alpha channel

---

# The "&.." Stuff simply means that other things can refer to yellow's value
#  by using "*title-color". If you change the value of yellow, you cange the
#  value of those other things as well.

yellow: &title-color
  [150,150,150]

log-to-console: True

game:
  resolution: [980,640]
  caption:    "Knights"
  fps-limit:  60


mainmenu:
  resolution:       [500,830]
  bgcolor:          [20,20,20]
  title:            "Main Menu"
  title-size:       [600,100]
  title-center-y:   50
  title-color:      *title-color
  title-bgcolor:    [20,20,20,0]
  title-text-size:  35
  button-padding:   25
  start-button-text:         "Start Game"
  highscore-button-text:     "Highscores"
  help-button-text:          "Help"
  exit-button-text:          "EXXXIT"

gameboard-logic:
  starting-position: [1,1]
  block-percentage:   45

pygame-field:
  error-length: 10

board:
  base:    images/base.png    # This image is put on top of every image
  open:    images/open.png
  knight:  images/knight.png
  visited: images/visited.png
  block:   images/block.png
  error:   images/error.png


clickToContinue:
  alpha:      200
  bgcolor:    [0,0,0]
  font:       "dejavuserif"
  font-size:  50
  bold:       true
  text-color: *title-color

freemode:
  bgcolor: [150,150,150]

scoremode:
  gametime:         50
  pause-color:      [0,0,0]
  pause-text-color: *title-color
  pause-alpha:      200
  pause-text:       "Click to un-pause"
  base-score:       78

levelbox:
  height:     110
  location:   [0,0]
  text-color: [150,150,150]
  bgcolor:    [150, 150, 150,0]
  text-size:  33

timebox:
  height:     110
  location:   [0,110]
  text-color: [20,20,20]
  bgcolor:    [150, 150, 150]
  text-size:  33

scorebox:
  height:     110
  location:   [0,220]
  text-color: [150,150,150]
  bgcolor:    [150, 150, 150,0]
  text-size:  33

sidebar:
  bgcolor:       [20,20,20]
  button-margin: 15
  button-height: 60
  pause-text:    "Pause"
  restart-text:  "Restart"
  mainmenu-text: "Main Menu"
  quit-text:     "Exit Game"
  board-padding: 5

button:
  bgcolor:       [200,160,80]
  hover-color:   [239,178,91]
  clicked_color: [71 ,154,60]
  font:          "dejavuserif"
  font-size:     20
  bold:          true
  text-color:    [0,0,0]

textbox:
  default-font:  "dejavuserif"
  default-bold:  True

highscore:
  bgcolor:          [20,20,20]
  show-n-scores:    10
  title-text:       "Highscores"
  title-size:       [700,70]
  title-text-color: *title-color
  title-bgcolor:    [20,20,20]
  title-text-size:  35
  title-bold:       True
  score-size:       [700,30]
  score-text-color: [235,235,235]
  score-bgcolor:    [20,20,20]
  score-text-size:  25
  score-bold:       True
  score-font:       "monospace"
  score-separator:  " : "

...